apiVersion: v1
kind: Namespace
metadata:
  name: demoapp
  labels:
    name: demoapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: demoapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demodb-pvc
  namespace: demoapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodb
  namespace: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demodb
  template:
    metadata:
      namespace: demoapp
      labels:
        app: demodb
        namespace: demoapp
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: demodb
          image: chetanguptahcl/demodb:logs
          imagePullPolicy: Always
          args: ["--config=/etc/mongod.conf"]
          lifecycle:
            preStop:
              exec:
                command:
                  ["/bin/sh", "-c", "mongod --shutdown --dbpath=/db/demodb"]
          volumeMounts:
            - name: "demodb-data"
              mountPath: "/db/demodb"
            - name: "logs-data"
              mountPath: "/logs"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
      volumes:
        - name: "demodb-data"
          persistentVolumeClaim:
            claimName: "demodb-pvc"
        - name: "logs-data"
          persistentVolumeClaim:
            claimName: "logs-pvc"

---
apiVersion: v1
kind: Service
metadata:
  name: demodb-service
  namespace: demoapp
spec:
  type: ClusterIP
  selector:
    app: demodb
  ports:
    - port: 27017
      targetPort: 27017
