apiVersion: v1
kind: Secret
metadata:
  name: dbinterface-secret
  namespace: demoapp
type: Opaque
data:
  dbusername: YXBwVXNlcg==
  dbpassword: YXBwVXNlcg==
  dbname: ZGVtb2Ri
  dbcollection: ZGVtb2NvbGxlY3Rpb24=
  dbport: MTUwMDA=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbinterface
  namespace: demoapp
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: dbinterface
  template:
    metadata:
      labels:
        app: dbinterface
        namespace: demoapp
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: dbinterface
          image: chetanguptahcl/dbinterface:logs
          imagePullPolicy: Always
          env:
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: dbinterface-secret
                  key: dbport
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dbinterface-secret
                  key: dbusername
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: dbinterface-secret
                  key: dbpassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: dbinterface-secret
                  key: dbname
            - name: DB_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: dbinterface-secret
                  key: dbcollection
          volumeMounts:
            - name: "logs-data"
              mountPath: "/logs"
          resources:
            limits:
              memory: "1Gi"
              cpu: "300m"
          ports:
            - name: dbinterface
              containerPort: 15000
            - name: metrics
              containerPort: 20000
      volumes:
        - name: "logs-data"
          persistentVolumeClaim:
            claimName: "logs-pvc"

---
apiVersion: v1
kind: Service
metadata:
  name: dbinterface-service
  namespace: demoapp
spec:
  selector:
    app: dbinterface
    namespace: demoapp
  ports:
    - port: 15000
      targetPort: 15000
